// https://umijs.org/config/
import { defineConfig } from 'umi';
import defaultSettings from './defaultSettings';
import proxy from './proxy';
const { REACT_APP_ENV } = process.env;
export default defineConfig({
  hash: true,
  antd: {},
  dva: {
    hmr: true,
  },
  layout: {
    // https://umijs.org/zh-CN/plugins/plugin-layout
    locale: true,
    siderWidth: 270,
    ...defaultSettings,
  },
  // https://umijs.org/zh-CN/plugins/plugin-locale
  locale: {
    default: 'vi-VN',
    antd: true,
    // default true, when it is true, will use `navigator.language` overwrite default
    baseNavigator: false,
  },
  dynamicImport: {
    loading: '@ant-design/pro-layout/es/PageLoading',
  },
  targets: {
    ie: 11,
  },
  // umi routes: https://umijs.org/docs/routing
  routes: [
    {
      path: '/user',
      layout: false,
      routes: [
        {
          path: '/user/login',
          layout: false,
          name: 'login',
          component: './user/Login',
        },
        {
          name: 'login',
          path: '/user/autologin',
          layout: false,
          hideInMenu: true,
          component: './user/AutoLogin',
        },
        {
          path: '/user',
          redirect: '/user/login',
        },
        {
          name: 'register-result',
          icon: 'smile',
          path: '/user/register-result',
          component: './user/register-result',
        },
        {
          name: 'register',
          icon: 'smile',
          path: '/user/register',
          component: './user/AccountRegister',
        },
        {
          name: 'forgetAcc',
          icon: 'smile',
          path: '/user/forgetAcc',
          component: './user/ForgetAcc',
          layout: false,
          hideInMenu: true,
        },
        {
          component: '404',
        },
      ],
    },
    {
      hideInMenu: true,

      name: 'account',
      icon: 'user',
      path: '/account',
      routes: [
        {
          name: 'center',
          icon: 'smile',
          path: '/account/center',
          component: './account/center',
        },
        {
          name: 'settings',
          icon: 'smile',
          path: '/account/settings',
          component: './account/settings',
        },
      ],
    },
    // {
    //   name: 'Dashboard',
    //   icon: 'dashboard',
    //   path: '/dashboard',
    //   component: './TrangChu',
    //   access: 'routeFilter',
    //   maChucNang: 'TRANG_CHU',
    // },
    {
      path: '/dashboard',
      name: 'Dashboard',
      icon: 'LineChartOutlined',
      component: './NoiBo',
      access: 'routeFilter',
      maChucNang: 'DASHBOARD',
      // component: './user/AutoLogin/loginlanding',
    },
    {
      path: '/landing',
      name: 'Giới thiệu',
      icon: 'project',
      component: './user/AutoLogin/loginlanding',
    },
    {
      path: '/',
      exact: true,
      hideInMenu: true,
      component: './WelcomePage',
    },
    {
      name: 'Truong',
      icon: 'bank',
      path: '/truong',
      access: 'routeFilter',
      maChucNang: 'TRUONG',
      routes: [
        {
          name: 'ThongTinTruong',
          path: './thongtintruong',
          component: './QuanLyTruong/components/TruongGiaoVien',
          access: 'routeFilter',
          maChucNang: 'THONG_TIN_TRUONG',
        },
      ],
    },
    {
      name: 'QuanLyTruong',
      icon: 'bank',
      path: './quanlytruong',
      component: './QuanLyTruong',
      access: 'routeFilter',
      maChucNang: 'QUAN_LY_TRUONG',
    },
    // {
    //   name: 'Quản lý thanh toán',
    //   icon: 'bank',
    //   path: './quanlythanhtoan',
    //   access: 'routeFilter',
    //   maChucNang: 'QUAN_LY_THANH_TOAN',
    //   routes: [
    //     {
    //       name: 'Gói thanh toán',
    //       icon: 'bank',
    //       path: './goithanhtoan',
    //       component: './GoiThanhToan',
    //       access: 'routeFilter',
    //       maChucNang: 'GOI_THANH_TOAN',
    //     },
    //     {
    //       name: 'Lịch sử thanh toán',
    //       icon: 'bank',
    //       path: './lichsucanhan',
    //       component: './LichSuThanhToan',
    //       access: 'routeFilter',
    //       maChucNang: 'LICH_SU_THANH_TOAN_NGDUNG',
    //     },
    //     {
    //       name: 'Lịch sử thanh toán',
    //       icon: 'bank',
    //       path: './lichsuadmin',
    //       component: './LichSuThanhToan',
    //       access: 'routeFilter',
    //       maChucNang: 'LICH_SU_THANH_TOAN_ADMIN',
    //     },
    //   ],
    // },
    {
      name: 'QuanLyLop',
      icon: 'home',
      path: '/quanlylop',
      component: './QuanLyLop',
      access: 'routeFilter',
      maChucNang: 'QUAN_LY_LOP',
    },
    {
      hideInMenu: true,
      exact: true,
      path: '/quanlylop/:id',
      component: './QuanLyLop/$id',
      access: 'routeFilter',
      maChucNang: 'CHI_TIET_LOP',
    },
    {
      name: 'QuanLyTrongMuon',
      icon: 'ClockCircleOutlined',
      path: '/quanlytrongmuon',
      component: './QuanLyTrongMuon',
      access: 'routeFilter',
      maChucNang: 'QUAN_LY_TRONG_MUON',
    },
    // {
    //   name: 'DangKyTrongMuon',
    //   icon: 'ClockCircleOutlined',
    //   path: '/dangkytrongmuon',
    //   component: './QuanLyTrongMuon',
    //   access: 'routeFilter',
    //   maChucNang: 'QUAN_LY_TRONG_MUON',
    // },
    {
      name: 'QuangCao',
      path: './quanlytin',
      component: './QuangCao',
      access: 'routeFilter',
      icon: 'HighlightOutlined',
      maChucNang: 'QUANG_CAO',
    },
    {
      name: 'QuanLyTuongTac',
      icon: 'UserSwitchOutlined',
      path: '/quanlytuongtac',
      access: 'routeFilter',
      maChucNang: 'QUAN_LY_TUONG_TAC',
      routes: [
        {
          name: 'QuanLyTinTuc',
          path: './quanlytintuc',
          component: './TinTucMamNon',
          access: 'routeFilter',
          maChucNang: 'QUAN_LY_TIN_TUC',
        },
        {
          name: 'QuanLyKhaoSat',
          path: './quanlykhaosat',
          access: 'routeFilter',
          maChucNang: 'QUAN_LY_KHAO_SAT',
          component: './QuanLyKhaoSat',
        },
        {
          name: 'HoatDongNgoaiKhoa',
          path: './hoatdongngoaikhoa',
          component: './HoatDongNgoaiKhoa',
          access: 'routeFilter',
          maChucNang: 'HOAT_DONG_NGOAI_KHOA',
        },
        {
          hideInMenu: true,
          exact: true,
          path: './hoatdongngoaikhoa/:id',
          component: './HoatDongNgoaiKhoa/$id',
          access: 'routeFilter',
          maChucNang: 'DS_LOP_HOAT_DONG_NGOAI_KHOA',
        },
        {
          name: 'QuanLyDon',
          path: './quanlydon',
          access: 'routeFilter',
          maChucNang: 'QUAN_LY_DON',
          routes: [
            {
              name: 'DonXinNghiHoc',
              icon: 'table',
              path: './donxinnghihoc',
              access: 'routeFilter',
              maChucNang: 'DON_XIN_NGHI_HOC',
              component: './QuanLyDon/DonXinNghi',
            },
            {
              name: 'DonDanDonVe',
              icon: 'table',
              path: './dondandonve',
              access: 'routeFilter',
              maChucNang: 'DON_DAN_DON_VE',
              component: './QuanLyDon/DanDonVe',
            },
            {
              name: 'DonDanThuoc',
              icon: 'table',
              path: './dondanthuoc',
              access: 'routeFilter',
              maChucNang: 'DON_DAN_THUOC',
              component: './QuanLyDon/DonDanThuoc',
            },
            {
              name: 'LoiDanCuaPhuHuynh',
              icon: 'table',
              path: './loinhancuaphuhuynh',
              access: 'routeFilter',
              maChucNang: 'LOI_NHAN_PHU_HUYNH',
              component: './QuanLyDon/LoiDanCuaPhuHuynh',
            },
          ],
        },
      ],
    },

    // {
    //   name: 'QuanLyDiemDanhPhuHuynh',
    //   icon: 'table',
    //   path: '/quanlydiemdanhphuhuynh',
    //   access: 'routeFilter',
    //   maChucNang: 'QUAN_LY_DIEM_DANH_PHU_HUYNH',
    //   routes: [
    //     {
    //       name: 'DiemDanhDauGioPhuHuynh',
    //       icon: 'table',
    //       path: './diemdanhdaugiophuhuynh',
    //       access: 'routeFilter',
    //       maChucNang: 'DIEM_DANH_DAU_GIO_PHU_HUYNH',
    //       component: './QuanLyDiemDanh/DiemDanhPhuHuynh',
    //     },
    //     {
    //       name: 'DiemDanhDonCon',
    //       icon: 'table',
    //       path: './diemdanhdoncon',
    //       access: 'routeFilter',
    //       maChucNang: 'DIEM_DANH_DON_CON',
    //       component: './QuanLyDiemDanh/DiemDanhPhuHuynh/components/DiemDanhDonCon',
    //     },
    //   ],
    // },

    {
      icon: 'schedule',
      path: './danhgiagiaovien/:id',
      access: 'routeFilter',
      maChucNang: 'DANH_SACH_GIAO_VIEN_DANH_GIA',
      component: './QuanLyDanhGia/DanhGiaGiaoVien/$id',
    },
    {
      icon: 'schedule',
      path: './danhgiadinhkyhocsinh/:id',
      access: 'routeFilter',
      maChucNang: 'DANH_SACH_HOC_SINH_DANH_GIA',
      component: './QuanLyDanhGia/DanhGiaHocSinh/$id',
    },
    // {
    //   name: 'DotDanhGiaSucKhoe',
    //   icon: 'ForkOutlined',
    //   path: '/dotdanhgiasuckhoe',
    //   access: 'routeFilter',
    //   maChucNang: 'QUAN_LY_DOT_DANH_GIA_SUC_KHOE',
    //   component: './DotDanhGiaSucKhoe',
    // },
    {
      name: 'QuanLyLichHoc',
      icon: 'solution',
      path: '/quanlylichhoc',
      access: 'routeFilter',
      maChucNang: 'QUAN_LY_LICH_HOC',
      routes: [
        {
          name: 'LichHoc',
          icon: 'table',
          path: './lichhoc',
          component: './QuanLyLichHoc',
          access: 'routeFilter',
          maChucNang: 'LICH_HOC',
        },
        {
          name: 'LichHoc.Template',
          icon: 'table',
          path: './lichhoctemplate',
          component: './QuanLyTemplateLichHoc',
          access: 'routeFilter',
          maChucNang: 'TEMPLATE_LICH_HOC',
        },
        {
          name: 'ThongTinDaoTao',
          icon: 'team',
          path: './thongtindaotao',
          access: 'routeFilter',
          maChucNang: 'THONG_TIN_DAO_TAO',
          routes: [
            {
              name: 'PhuongPhapGiaoDuc',
              icon: 'team',
              path: './phuongphapgiaoduc',
              component: './ChuongTrinhDaoTao',
              access: 'routeFilter',
              maChucNang: 'PHUONG_PHAP_GIAO_DUC',
            },
            {
              name: 'LinhVucPhatTrien',
              icon: 'FileDoneOutlined',
              path: './linhvucphattrien',
              component: './QuanLyMonHoc',
              access: 'routeFilter',
              maChucNang: 'LINH_VUC_PHAT_TRIEN',
            },
            {
              name: 'QuanLyBaiHoc',
              icon: 'table',
              path: './quanlybaihoc',
              component: './QuanLyBaiHoc',
              access: 'routeFilter',
              maChucNang: 'QUAN_LY_BAI_HOC',
            },
          ],
        },
      ],
    },
    {
      name: 'NangCapTaiKhoan',
      icon: 'upload',
      path: '/nangcaptaikhoan',
      component: './NangCapTaiKhoan',
      access: 'routeFilter',
      maChucNang: 'NANG_CAP_TAI_KHOAN',
    },
    {
      name: 'KhaiBaoThongTin',
      icon: 'user',
      path: '/khaibaothongtin',
      access: 'routeFilter',
      maChucNang: 'KHAI_BAO_THONG_TIN',
      routes: [
        {
          name: 'ThongTinCaNhan',
          icon: 'table',
          path: '/khaibaothongtin/thongtincanhan',
          component: './KhaiBaoThongTin',
          access: 'routeFilter',
          maChucNang: 'THONG_TIN_CA_NHAN',
        },
        {
          name: 'ThongTinCon',
          icon: 'table',
          path: '/khaibaothongtin/thongtincon',
          component: './KhaiBaoThongTin/components/ThongTinCon.tsx',
          access: 'routeFilter',
          maChucNang: 'THONG_TIN_CON',
        },
      ],
    },
    {
      name: 'ChucNangPhuHuynh',
      icon: 'profile',
      path: '/chucnangphuhuynh',
      component: './ChucNangPhuHuynh',
      access: 'routeFilter',
      maChucNang: 'CHUC_NANG_PHU_HUYNH',
    },
    // {
    //   name: 'ChucNangGiaoVien',
    //   icon: 'table',
    //   path: '/chucnanggiaovien',
    //   component: './ChucNangGiaoVien',
    //   access: 'GiaoVien',
    // },
    {
      name: 'QuanLyThucPham',
      icon: 'shop',
      path: '/quanlythucpham',
      access: 'routeFilter',
      maChucNang: 'QUAN_LY_THUC_PHAM',
      routes: [
        {
          name: 'DanhMucThucPham',
          path: './danhmucthucpham',
          access: 'routeFilter',
          maChucNang: 'DANH_MUC_THUC_PHAM',
          component: './ThucPham/DanhMucThucPham',
        },
        {
          name: 'QuyDoi',
          path: './quydoi',
          access: 'routeFilter',
          maChucNang: 'QUY_DOI',
          component: './QuyDoi',
        },
        {
          name: 'TienThua',
          path: './tienthua',
          access: 'routeFilter',
          maChucNang: 'QUAN_LY_TIEN_THUA',
          component: './ThucPham/TienThua',
        },
        {
          name: 'DanhMucMonAn',
          path: './danhmucmonan',
          access: 'routeFilter',
          maChucNang: 'DANH_MUC_MON_AN',
          component: './ThucPham/DanhMucMonAn',
        },
        {
          name: 'ThucPhamKho',
          path: './thucphamkho',
          access: 'routeFilter',
          maChucNang: 'THUC_PHAM_KHO',
          component: './ThucPham/ThucPhamKho',
        },
        {
          name: 'HoaDon',
          path: './hoadon',
          access: 'routeFilter',
          maChucNang: 'HOA_DON',
          component: './ThucPham/HoaDon',
        },
        {
          name: 'QuyDinhChung',
          path: './quydinhchung',
          access: 'routeFilter',
          maChucNang: 'QUY_DINH_CHUNG',
          routes: [
            {
              name: 'BangDinhDuong',
              path: './quydinhdinhduong',
              access: 'routeFilter',
              maChucNang: 'BANG_DINH_DUONG',
              component: './ThucPham/BangDinhDuong',
            },
            {
              name: 'QuyDinhThucDon',
              path: './quydinhthucdon',
              access: 'routeFilter',
              maChucNang: 'QUY_DINH_THUC_DON',
              component: './ThucPham/QuyDinhThucDon',
            },
          ],
        },

        {
          name: 'KiemThu',
          path: './kiemthubabuoc',
          access: 'routeFilter',
          maChucNang: 'KIEM_THU',
          component: './ThucPham/KiemThu',
        },
        {
          name: 'KhauPhanAn',
          path: './khauphanan',
          access: 'routeFilter',
          maChucNang: 'KHAU_PHAN_AN',
          component: './ThucPham/KhauPhanAn',
        },
        {
          name: 'LenThucDonMau',
          path: './lenthucdonmau',
          access: 'routeFilter',
          maChucNang: 'LEN_THUC_DON_MAU',
          component: './ThucPham/LenThucDonMau',
        },
      ],
    },
    {
      name: 'ThongBao',
      icon: 'notification',
      path: '/thongbao',
      access: 'routeFilter',
      maChucNang: 'THONG_BAO',
      component: './ThongBao',
    },
    {
      name: 'AlbumAnh',
      icon: 'FileImageOutlined',
      path: '/album-anh',
      access: 'routeFilter',
      maChucNang: 'ALBUM_ANH',
      component: './AlbumAnh',
    },
    {
      name: 'QuanLyGiaoVien',
      icon: 'EditFilled',
      path: '/quanlygiaovien',
      access: 'routeFilter',
      maChucNang: 'QUAN_LY_GIAO_VIEN',
      routes: [
        {
          name: 'Thông tin lương',
          path: '/quanlygiaovien/hosogiaovien',
          component: './QuanLyTaiKhoan/TaiKhoanGiaoVien',
          access: 'routeFilter',
          maChucNang: 'HO_SO_GIAO_VIEN',
        },
        {
          name: 'Quản lý hồ sơ giáo viên chi tiết',
          path: '/quanlygiaovien/hosogiaovien/:id',
          hideInMenu: true,
          component: './QuanLyTaiKhoan/TaiKhoanGiaoVien/$id',
          access: 'routeFilter',
          maChucNang: 'HO_SO_GIAO_VIEN',
        },
        {
          name: 'DiemDanhGiaoVien',
          path: './diemdanhgiaovien',
          component: './QuanLyDiemDanh/DiemDanhGiaoVien',
          access: 'routeFilter',
          maChucNang: 'DIEM_DANH_GIAO_VIEN',
        },
        {
          name: 'ThongKeLuong',
          path: './thongkeluong',
          component: './ThongKeLuong',
          access: 'routeFilter',
          maChucNang: 'THONG_KE_LUONG',
        },
        {
          name: 'DanhGiaGiaoVien',
          path: './danhgiagiaovien',
          access: 'routeFilter',
          component: './QuanLyDanhGia/DanhGiaGiaoVien',
          maChucNang: 'DANH_GIA_GIAO_VIEN',
        },
      ],
    },
    {
      name: 'QuanLyHocSinh',
      icon: 'CopyFilled',
      path: '/quanlyhocsinh',
      access: 'routeFilter',
      maChucNang: 'QUAN_LY_HOC_SINH',
      routes: [
        {
          name: 'ThongTinHocPhi',
          path: './thongtinhocphi',
          component: './ThongTinHocPhi',
          access: 'routeFilter',
          maChucNang: 'HOC_PHI',
        },
        {
          hideInMenu: true,
          exact: true,
          path: './thongtinhocphi/:id',
          component: './ThongTinHocPhi/$id',
          access: 'routeFilter',
          maChucNang: 'HOC_PHI',
        },
        {
          name: 'DanhGiaDinhKyHocSinh',
          icon: 'schedule',
          path: './danhgiadinhkyhocsinh',
          access: 'routeFilter',
          maChucNang: 'DANH_GIA_HOC_SINH',
          component: './QuanLyDanhGia/DanhGiaHocSinh',
        },
        {
          name: 'QuanLyDiemDanh',
          icon: 'ordered-list',
          path: './quanlydiemdanh',
          access: 'routeFilter',
          maChucNang: 'QUAN_LY_DIEM_DANH',
          routes: [
            {
              name: 'DiemDanh',
              icon: 'table',
              path: './diemdanh',
              component: './QuanLyDiemDanh/DiemDanh',
              access: 'routeFilter',
              maChucNang: 'DIEM_DANH',
            },
            {
              hideInMenu: true,
              exact: true,
              path: './diemdanh/:id',
              component: './QuanLyDiemDanh/DiemDanh/$id',
              access: 'routeFilter',
              maChucNang: 'CHI_TIET_LOP_DIEM_DANH',
            },
            {
              name: 'DiemDanhMuon',
              icon: 'table',
              path: './diemdanhmuon',
              component: './QuanLyDiemDanh/DiemDanhMuon',
              access: 'routeFilter',
              maChucNang: 'DIEM_DANH_MUON',
            },
          ],
        },
      ],
    },
    {
      name: 'QuanLyBaoCao',
      icon: 'ContainerOutlined',
      path: '/quanlybaocao',
      access: 'routeFilter',
      maChucNang: 'QUAN_LY_BAO_CAO',
      routes: [
        {
          name: 'BaoCaoSBN',
          path: './baocaosobannganh',
          access: 'routeFilter',
          maChucNang: 'BAO_CAO_SBN',
          component: './QuanLyBaoCao/BaoCaoSBN',
        },
        {
          name: 'BaoCaoHeThong',
          path: './baocaohethong',
          access: 'routeFilter',
          maChucNang: 'BAO_CAO_HE_THONG',
          component: './QuanLyBaoCao/BaoCaoHeThong',
        },
        // {
        //   name: 'BaoCaoNoiBo',
        //   path: './baocaonoibo',
        //   access: 'routeFilter',
        //   maChucNang: 'BAO_CAO_NOI_BO',
        //   component: './NoiBo',
        // },
      ],
    },

    {
      name: 'DoanhThu',
      icon: 'DollarOutlined',
      path: '/doanhthu',
      access: 'routeFilter',
      maChucNang: 'DOANH_THU',
      component: './DoanhThu',
    },
    // {
    //   name: 'NoiBo',
    //   icon: 'DollarOutlined',
    //   path: '/noibo',
    //   access: 'routeFilter',
    //   maChucNang: 'DOANH_THU',
    //   component: './NoiBo',
    // },
    {
      name: 'QuanLyTaiSan',
      icon: 'MoneyCollectOutlined',
      path: '/quanlytaisan',
      access: 'routeFilter',
      maChucNang: 'QUAN_LY_TAI_SAN',
      routes: [
        {
          name: 'DanhMucTaiSan',
          icon: 'table',
          path: './danhmuctaisan',
          component: './QuanLyTaiSan/DanhMucTaiSan',
          access: 'routeFilter',
          maChucNang: 'DANH_MUC_TAI_SAN',
        },
        {
          name: 'BaoHongSuaChua',
          icon: 'table',
          path: './baohongsuachua',
          component: './QuanLyTaiSan/BaoHong',
          access: 'routeFilter',
          maChucNang: 'BAO_HONG',
        },
      ],
    },
    {
      name: 'QuanLyTaiKhoan',
      icon: 'team',
      path: '/quanlytaikhoan',
      access: 'routeFilter',
      maChucNang: 'QUAN_LY_TAI_KHOAN',
      routes: [
        {
          name: 'TaiKhoanChuTruong',
          path: '/quanlytaikhoan/taikhoanchutruong',
          component: './QuanLyTaiKhoan/TaiKhoanChuTruong',
          access: 'routeFilter',
          maChucNang: 'TAI_KHOAN_CHU_TRUONG',
        },
        {
          name: 'TaiKhoanHieuTruong',
          path: '/quanlytaikhoan/taikhoanhieutruong',
          component: './QuanLyTaiKhoan/TaiKhoanHieuTruong',
          access: 'routeFilter',
          maChucNang: 'TAI_KHOAN_HIEU_TRUONG',
        },
        {
          name: 'TaiKhoanGiaoVien',
          path: '/quanlytaikhoan/taikhoangiaovien',
          component: './QuanLyTaiKhoan/TaiKhoanGiaoVien',
          access: 'routeFilter',
          maChucNang: 'TAI_KHOAN_GIAO_VIEN',
        },
        {
          name: 'TaiKhoanGiaoVien',
          path: '/quanlytaikhoan/taikhoangiaovien/:id',
          component: './QuanLyTaiKhoan/TaiKhoanGiaoVien/$id',
          access: 'routeFilter',
          maChucNang: 'TAI_KHOAN_GIAO_VIEN',
          hideInMenu: true,
          exact: true,
        },
        {
          name: 'TaiKhoanPhuHuynh',
          path: '/quanlytaikhoan/taikhoanphuhuynh',
          component: './QuanLyTaiKhoan/TaiKhoanPhuHuynh',
          access: 'routeFilter',
          maChucNang: 'TAI_KHOAN_PHU_HUYNH',
        },
        {
          name: 'TaiKhoanPhuHuynh',
          path: '/quanlytaikhoan/taikhoanphuhuynh/:id',
          component: './QuanLyTaiKhoan/TaiKhoanPhuHuynh/$id',
          access: 'routeFilter',
          maChucNang: 'TAI_KHOAN_PHU_HUYNH',
          hideInMenu: true,
          exact: true,
        },
        {
          name: 'TaiKhoanKhach',
          path: '/quanlytaikhoan/taikhoankhach',
          component: './QuanLyTaiKhoan/TaiKhoanKhach',
          access: 'routeFilter',
          maChucNang: 'TAI_KHOAN_KHACH',
        },
        {
          name: 'TaiKhoanPhuHuynh',
          path: '/quanlytaikhoan/taikhoankhach/:id',
          component: './QuanLyTaiKhoan/TaiKhoanPhuHuynh/$id',
          access: 'routeFilter',
          maChucNang: 'TAI_KHOAN_KHACH',
          hideInMenu: true,
          exact: true,
        },
      ],
    },
    {
      name: 'QuanTriPhanQuyen',
      icon: 'table',
      path: 'quantriphanquyen',
      access: 'routeFilter',
      maChucNang: 'QUAN_TRI_PHAN_QUYEN',
      routes: [
        {
          name: 'VaiTroQuanLy',
          path: './vaitroquanly',
          component: './QuanTriPhanQuyen/VaiTroQuanTri',
          access: 'routeFilter',
          maChucNang: 'VAI_TRO_QUAN_LY',
        },
        {
          name: 'ChucNangQuanTri',
          path: './chucnangquanly',
          component: './QuanTriPhanQuyen/ChucNangQuanTri',
          access: 'routeFilter',
          maChucNang: 'CHUC_NANG_QUAN_LY',
        },
      ],
    },
    {
      name: 'BaoCaoQuanTri',
      icon: 'table',
      path: 'baocaoquantri',
      access: 'routeFilter',
      maChucNang: 'BAO_CAO_QUAN_TRI',
      component: './BaoCaoQuanTri',
    },
    {
      name: 'QuanLyCauHinh',
      icon: 'setting',
      path: 'quanlycauhinh',
      access: 'routeFilter',
      maChucNang: 'QUAN_LY_CAU_HINH',
      component: './QuanLyCauHinh',
    },
    // {
    //   name: 'Calendar',
    //   icon: 'CalendarOutlined',
    //   path: '/calendar',
    //   component: './Calendar',
    // },
    // {
    //   name: 'News',
    //   icon: 'FileDoneOutlined',
    //   path: '/quan-ly-tin-tuc',
    //   component: './QuanLyTinTuc',
    // },
    // {
    //   name: 'Structure',
    //   icon: 'table',
    //   path: '/chuongtrinhkhung',
    //   component: './ChuongTrinhKhung',
    //   access: 'sinh_vien',
    // },
    // {
    //   name: 'LopTinChi',
    //   icon: 'team',
    //   path: '/loptinchi',
    //   component: './LopTinChi',
    //   access: 'sinh_vien',
    // },
    // {
    //   name: 'LopHanhChinh',
    //   icon: 'team',
    //   path: '/lophanhchinh',
    //   component: './LopHanhChinh',
    //   access: 'sinh_vien',
    // },
    // {
    //   hideInMenu: true,
    //   icon: 'team',
    //   exact: true,
    //   access: 'sinh_vien',
    //   path: '/loptinchi/:id',
    //   component: './LopTinChi/$id',
    // },
    {
      component: '404',
    },
  ],
  // Theme for antd: https://ant.design/docs/react/customize-theme-cn
  theme: {
    'primary-color': defaultSettings.primaryColor,
  },
  // esbuild is father build tools
  // https://umijs.org/plugins/plugin-esbuild
  esbuild: {},
  title: false,
  ignoreMomentLocale: true,
  proxy: proxy[REACT_APP_ENV || 'dev'],
  manifest: {
    basePath: '/',
  },
  // Fast Refresh 热更新
  fastRefresh: {},

  nodeModulesTransform: {
    type: 'none',
  },
  // mfsu: {},
  webpack5: {},
  exportStatic: {},
});
